output_file=open("test","w")
output_file.write('<html>')
output_file.write('    <body>')
output_file.write('      <h1>My First Heading</h1>')
output_file.write('      <p>My first paragraph.</p>')
output_file.write('    </body>')
output_file.write('</html>')